apps/profiles/urls.py
__author__ = 'PerminovMA@live.ru'

from django.conf.urls import url

urlpatterns = [
    url(r'registration', 'profiles.views.user_registration', name='registration'),
    url(r'authorization', 'profiles.views.user_authorization', name='authorization'),
    url(r'logout', 'django.contrib.auth.views.logout', {'next_page': 'index'}, name='logout'),
]

ew/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from profiles import urls as profiles_urls
from eworld import urls as eworld_urls
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='eworld/index.html'), name='index'),
    url(r'^eworld/', include(eworld_urls, namespace='eworld')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^profile/', include(profiles_urls, namespace='profile')),
    url(r'^angular_urls_config$', TemplateView.as_view(template_name='eworld/js/urls_config.js'),
        name='angular_urls_config'),
    # url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                           document_root=settings.STATIC_ROOT)  # Only for development (not production).

apps/profiles/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from eworld.utils import generate_filename
from random import randint
from django.conf import settings
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver
from django.utils.translation import ugettext_lazy as _


class Country(models.Model):
    name = models.CharField(max_length=30)

    def __unicode__(self):
        return self.name


class City(models.Model):
    name = models.CharField(max_length=30)
    country = models.ForeignKey(Country)

    def __unicode__(self):
        return self.name


def get_upload_avatar_path(instance, filename):
    return "avatars/%s/%s/" % (str(randint(1, settings.COUNT_FOLDERS)),
                               str(randint(1, settings.COUNT_FOLDERS))) + generate_filename(filename)


class UserProfile(AbstractUser):
    phone_number = models.CharField(max_length=15, null=True, blank=True)
    is_banned = models.BooleanField(default=False)
    cities = models.ManyToManyField(City)
    about_me = models.TextField(null=True, blank=True)
    avatar = models.ImageField(null=True, blank=True, upload_to=get_upload_avatar_path)
    AbstractUser._meta.get_field('email')._unique = True  # Make email field unique

    @property
    def is_client(self):
        return hasattr(self, 'client')

    @property
    def is_event_manager(self):
        try:
            return self.event_manager is not None
        except EventManager.DoesNotExist:
            return False

    def save(self, *args, **kwargs):
        """ delete old avatar when replacing by updating the file """
        try:
            this = UserProfile.objects.get(id=self.id)
            if this.avatar != self.avatar:
                this.avatar.delete(save=False)
        except UserProfile.DoesNotExist:
            pass  # When new photo then we do nothing, normal case
        super(UserProfile, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.username


@receiver(pre_delete, sender=UserProfile)
def user_profile_avatar_delete(sender, instance, **kwargs):
    """ delete avatar when remove UserProfile object from admin panel """
    instance.avatar.delete(False)


class Client(models.Model):
    user = models.OneToOneField(UserProfile)
    activity_index = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)

    def __unicode__(self):
        return u'Client %s' % self.user


class EventManager(models.Model):
    INDIVIDUAL_PERSON = 'INDIVIDUAL'
    LEGAL_PERSON = 'LEGAL'
    LEGAL_STATUSES = ((LEGAL_PERSON, 'Legal person'), (INDIVIDUAL_PERSON, 'Individual person'))
    legal_status = models.CharField(choices=LEGAL_STATUSES, max_length=10, default=INDIVIDUAL_PERSON)

    user = models.OneToOneField(UserProfile, related_name='event_manager')
    activity_index = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)

    def __unicode__(self):
        return u'Event manager %s' % self.user


class Message(models.Model):
    sender = models.ForeignKey(UserProfile, related_name='outgoing_messages_set')
    receiver = models.ForeignKey(UserProfile, related_name='incoming_messages_set')
    theme = models.CharField(max_length=150, null=True, blank=True)
    text = models.TextField()
    is_read = models.BooleanField(default=False)
    creation_datetime = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = (('sender', 'receiver'),)

    def __unicode__(self):
        return self.theme


class Portfolio(models.Model):
    categories = models.ManyToManyField('events.Category', blank=True)
    event_manager = models.ForeignKey(EventManager)
    creation_date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.event_manager.user.username + "'s portfolio. ID " + str(self.id)


def get_upload_image_path(instance, filename):
    return "portfolio_images/%s/%s/" % (str(randint(1, settings.COUNT_FOLDERS)),
                                        str(randint(1, settings.COUNT_FOLDERS))) + generate_filename(filename)


class PortfolioImage(models.Model):
    image = models.ImageField(upload_to=get_upload_image_path)
    portfolio = models.ForeignKey(Portfolio)

    def save(self, *args, **kwargs):
        """ delete old image when replacing by updating the file """
        try:
            this = PortfolioImage.objects.get(id=self.id)
            if this.image != self.image:
                this.image.delete(save=False)
        except PortfolioImage.DoesNotExist:
            pass  # When new photo then we do nothing, normal case
        super(PortfolioImage, self).save(*args, **kwargs)


@receiver(pre_delete, sender=PortfolioImage)
def portfolio_image_delete(sender, instance, **kwargs):
    """ delete image when remove object from admin panel """
    instance.image.delete(False)

apps/profiles/forms.py
# -*- coding: utf-8 -*-

from django import forms
from models import UserProfile
from django.utils.translation import ugettext as _

__author__ = 'PerminovMA@live.ru'


class RegistrationForm(forms.Form):
    CLIENT_LABEL = 'client'
    EVENT_MANAGER_LABEL = 'event_manager'

    username = forms.CharField(help_text="Username", max_length=30)
    first_name = forms.CharField(help_text="Имя", required=False)
    last_name = forms.CharField(help_text="Фамилия", required=False)
    email = forms.EmailField(help_text="Электронная почта")
    phone_number = forms.CharField(max_length=15, required=False, help_text="Телефон")
    user_type = forms.ChoiceField(
        choices=[(CLIENT_LABEL, u'Клиент'), (EVENT_MANAGER_LABEL, u'Организатор мероприятий')],
        initial='client', widget=forms.RadioSelect, required=True)
    password = forms.CharField(max_length=128, help_text="Пароль", widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data['username']
        if UserProfile.objects.filter(email=username).last():
            raise forms.ValidationError(_(u"Пользователь с таким именем уже зарегистрирован."),
                                        code="user_already_exist")
        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        if UserProfile.objects.filter(email=email).last():
            raise forms.ValidationError(_(u"Пользователь с такой электронной почтой уже зарегистрирован."),
                                        code="user_already_exist")
        return email

    def clean_password(self):
        password = self.cleaned_data['password']
        if len(password) < 6:
            raise forms.ValidationError(_(u"Минимальная длинна пароля 6 символов"), code="bad_password")
        return password

    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()
        phone_number = cleaned_data.get("phone_number")
        if phone_number == '':
            cleaned_data["phone_number"] = None


class EmailAuthorizationForm(forms.Form):
    email = forms.EmailField(help_text="Электронная почта")
    password = forms.CharField(max_length=128, help_text="Пароль", widget=forms.PasswordInput)

    def clean_email(self):
        email = self.cleaned_data['email']
        if not UserProfile.objects.filter(email__iexact=email).last():
            raise forms.ValidationError(_(u"Пользователь с такой электронной почтой не зарегистрирован."),
                                        code="user_not_exist")
        return email

apps/profiles/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import HttpResponse, render, Http404
from forms import RegistrationForm, EmailAuthorizationForm
from models import UserProfile, EventManager, Client
import json
from django import forms
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect


def user_registration(request):
    if request.method == "GET":
        form = RegistrationForm()
        return render(request, 'profiles/registration.html', {"form": form})
    elif request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user_obj = UserProfile(username=form.cleaned_data.get("username"),
                                   phone_number=form.cleaned_data.get("phone_number"),
                                   email=form.cleaned_data.get("email"), first_name=form.cleaned_data.get("first_name"),
                                   last_name=form.cleaned_data.get("last_name"))
            user_obj.set_password(form.cleaned_data.get("password"))
            user_obj.save()

            user_type = request.POST.get("user_type")
            if user_type == RegistrationForm.CLIENT_LABEL:
                Client.objects.create(user=user_obj)
            elif user_type == RegistrationForm.EVENT_MANAGER_LABEL:
                EventManager.objects.create(user=user_obj)  # TODO add legal_status and categories

            user = authenticate(username=user_obj.email, password=form.cleaned_data.get("password"))

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(reverse('eworld:dashboard'))
            return HttpResponse(u"Произошла ошибка. Пожалуйста, обратитесь к администратору.")
        else:
            return render(request, 'profiles/registration.html', {"form": form})
    else:
        raise Http404


def user_authorization(request):
    if request.user.is_authenticated():
        pass  # TODO redirect to success page

    if request.method == "GET":
        form = EmailAuthorizationForm()
        return render(request, 'profiles/authorization_modal.html', {"form": form})
    elif request.method == "POST":
        request_data = json.loads(request.body)  # angular specific
        form = EmailAuthorizationForm(request_data)

        if form.is_valid():
            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password")

            user = authenticate(username=email, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse(json.dumps({'result': 'ok', 'redirect_url': reverse('eworld:dashboard')}))

            form.add_error("password", forms.ValidationError('Email or password not valid'))

        req_data = {'result': 'nok', 'errors': form.errors}
        return HttpResponse(json.dumps(req_data))
    else:
        raise Http404


def logout(request):
    logout(request)
    return HttpResponse('logout')

apps/profiles/templates/profiles/authorization_modal.html
{% load staticfiles extra_filters %}

<div style="background-color: #ffffff;">
    <div class="modal-header">
        <h3 class="modal-title">Im a modal!</h3>
    </div>
    <div ng-if="form_errors.length > 0">
        <ul class="alert alert-danger">
          <li ng-repeat="error in form_errors" style="margin-left: 7rem;">[[error]]</li>
        </ul>
    </div>
    <div class="modal-body">

        <form method="POST" class="form-horizontal" ng-submit="submit()"> {% csrf_token %}
            {% for field in form %}
                <div class="form-group form-group-lg" ng-class="{'has-error': {{ field.name }}_error_status}">
                    <input ng-model="{{ field.name }}" value="{% if field.value %}{{ field.value }}{% endif %}" type="{{ field|get_field_type }}"
                           class="form-control" name="{{ field.name }}" id="{{ field.id_for_label }}"
                           placeholder="{{ field.help_text }}" required>
                </div>
            {% endfor %}

            {#                <div class="form-group">#}
            {#                    <div class="col-sm-offset-2 col-sm-10">#}
            {#                        <div class="checkbox">#}
            {#                            <label>#}
            {#                                <input type="checkbox"> Запомнить меня [[2+2]] [[namee]]#}
            {#                            </label>#}
            {#                        </div>#}
            {#                    </div>#}
            {#                </div>#}
            {#                <div class="form-group">#}
            {#                    <div class="col-sm-offset-2 col-sm-10">#}
            {#                        <a href="#">Забыли пароль?</a>#}
            {#                    </div>#}
            {#                </div>#}

            <div class="modal-footer text-center">

                [[1+1]]
                <button type="button" class="btn btn-default" ng-click="cancel()">Отмена</button>
                <button type="submit" id="submit" class="btn btn-default">Вход</button>
            </div>

        </form>

    </div>
</div>

apps/profiles/templates/profiles/registration.html
{% extends "eworld/base_template.html" %}
{% load staticfiles extra_filters %}

{% block body %}
<div class="registration">

    <!-- Modal -->
    <div class="modal fade" id="myOffer" tabindex="-1" role="dialog" aria-labelledby="myOfferLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
                    <h4 class="modal-title" id="myModalLabel">Договор Оферты</h4>
                </div>
                <div class="modal-body">
                    <h3>Updated November 14, 2008</h3>

                    <p class="lead">Your privacy is critically important to us. At Dribbble we have a few fundamental principles:</p>

                    <p>We don’t ask you for personal information unless we truly need it. (We can’t stand services that ask you for things like your gender or income level for no apparent reason.)</p>
                    <p>We don’t share your personal information with anyone except to comply with the law, develop our products, or protect our rights.</p>
                    <p>We don’t store personal information on our servers unless required for the on-going operation of one of our services.</p>
                    <p>Below is our privacy policy which incorporates these goals:</p>

                    <p>Dribbble LLC (Dribbble) operates dribbble.com. It is Dribbble’s policy to respect your privacy regarding any information we may collect while operating our websites.</p>

                    <h3>Website Visitors</h3>

                    <p>Like most website operators, Dribbble collects non-personally-identifying information of the sort that web browsers and servers typically make available, such as the browser type, language preference, referring site, and the date and time of each visitor request. Dribbble’s purpose in collecting non-personally identifying information is to better understand how Dribbble’s visitors use its website. From time to time, Dribbble may release non-personally-identifying information in the aggregate, e.g., by publishing a report on trends in the usage of its website.</p>

                    <p>Dribbble also collects potentially personally-identifying information like Internet Protocol (IP) addresses. Dribbble does not use such information to identify its visitors, however, and does not disclose such information, other than under the same circumstances that it uses and discloses personally-identifying information, as described below.</p>

                    <h3>Gathering of Personally-Identifying Information</h3>

                    <p>Certain visitors to Dribbbles websites choose to interact with Dribbble in ways that require Dribbble to gather personally-identifying information. The amount and type of information that Dribbble gathers depends on the nature of the interaction. For example, we ask visitors who sign up account at dribbble.com to provide a username and email address. Dribbble collects such information only insofar as is necessary or appropriate to fulfill the purpose of the visitors interaction with Dribbble. Dribbble does not disclose personally-identifying information other than as described below. And visitors can always refuse to supply personally-identifying information, with the caveat that it may prevent them from engaging in certain website-related activities.</p>

                    <h3>Aggregated Statistics</h3>

                    <p>Dribbble may collect statistics about the behavior of visitors to its websites. Dribbble may display this information publicly or provide it to others. However, Dribbble does not disclose personally-identifying information other than as described below.</p>

                    <h3>Protection of Certain Personally-Identifying Information</h3>

                    <p>Dribbble discloses potentially personally-identifying and personally-identifying information only to those of its employees, contractors and affiliated organizations that (i) need to know that information in order to process it on Dribbbles behalf or to provide services available at Dribbbles websites, and (ii) that have agreed not to disclose it to others. Some of those employees, contractors and affiliated organizations may be located outside of your home country; by using Dribbbles websites, you consent to the transfer of such information to them. Dribbble will not rent or sell potentially personally-identifying and personally-identifying information to anyone. Other than to its employees, contractors and affiliated organizations, as described above, Dribbble discloses potentially personally-identifying and personally-identifying information only when required to do so by law, or when Dribbble believes in good faith that disclosure is reasonably necessary to protect the property or rights of Dribbble, third parties or the public at large. If you are a registered user of an Dribbble website and have supplied your email address, Dribbble may occasionally send you an email to tell you about new features, solicit your feedback, or just keep you up to date with whats going on with Dribbble and our products. We primarily use our various product blogs to communicate this type of information, so we expect to keep this type of email to a minimum. If you send us a request (for example via a support email or via one of our feedback mechanisms), we reserve the right to publish it in order to help us clarify or respond to your request or to help us support other users. Dribbble takes all measures reasonably necessary to protect against the unauthorized access, use, alteration or destruction of potentially personally-identifying and personally-identifying information.</p>

                    <h3>Cookies</h3>

                    <p>A cookie is a string of information that a website stores on a visitors computer, and that the visitors browser provides to the website each time the visitor returns. Dribbble uses cookies to help Dribbble identify and track visitors, their usage of Dribbble website, and their website access preferences. Dribbble visitors who do not wish to have cookies placed on their computers should set their browsers to refuse cookies before using Dribbbles websites, with the drawback that certain features of Dribbbles websites may not function properly without the aid of cookies.</p>

                    <h3>Privacy Policy Changes</h3>

                    <p>Although most changes are likely to be minor, Dribbble may change its Privacy Policy from time to time, and in Dribbbles sole discretion. Dribbble encourages visitors to frequently check this page for any changes to its Privacy Policy. Your continued use of this site after any change in this Privacy Policy will constitute your acceptance of such change.</p>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
{#    <div class="modal fade" id="myRegisterOk" tabindex="-1" role="dialog" aria-labelledby="myRegisterOkLabel" aria-hidden="true">#}
{#        <div class="modal-dialog">#}
{#            <div class="modal-content">#}
{#                <div class="modal-body text-center">#}
{#                    <p class="lead ew-icon ew-icon-mail">Благодарим Вас за регистрацию на Eworld.</p>#}
{#                    <p>Осталось совсем чуть–чуть. Проверьте свою почту и нажмите ссылку для подтверждения регистрации.</p>#}
{#                </div>#}
{#                <div class="modal-footer text-center">#}
{#                    <button type="button" class="btn btn-default" data-dismiss="modal">OK</button>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}

<div class="container-fluid">

    <main id="page">

    {% block menu %} {{ block.super }} {% endblock %}

    <section id="content" class="">
        <header class="clearfix">
            <h1 class="ew-icon-organizer">Регистрация</h1>
            <div class="description col-lg-7 col-md-9">
            <p>Minimalist posters are encouraging us to be design idiots.</p>
            <p>A central tenet of good design is that it shouldn't be any more complicated than it needs to be, but that doesn't mean good design is inherently uncomplicated.</p>
            </div>
        </header>
        <div class="page-content col-lg-7 col-md-9 col-sm-10 col-xs-12">
        <form method="POST" class="" action="{% url 'profile:registration' %}"> {% csrf_token %}
            {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">{{ error }};</div>
                {% endfor %}
            {% endif %}
            {% for field in form %}
                <div class="form-group form-group-lg">
                    <label for="{{ field.id_for_label }}">{{ field.errors }}</label>

                  {% if field|get_field_type == "RadioSelect" %} {# additional labels only for RadioSelect #}
                      <p>Выберите тип пользователя:</p>
                      {{ field }}
                  {% else %}
                    <input value="{% if field.value %}{{ field.value }}{% endif %}" type="{{ field|get_field_type }}" class="form-control" name="{{ field.name }}" id="{{ field.id_for_label }}" placeholder="{{ field.help_text }}">
                  {% endif %}

                </div>
            {% endfor %}

            <div class="form-group form-group-lg">
                <label for="inputPasswordConfirm" class="sr-only control-label">Подтвердите пароль</label>
                <input type="Password" class="form-control" id="inputPasswordConfirm" placeholder="Подтвердите пароль">
            </div>

            <div class="form-group form-group-lg">
                <div class="checkbox">
                    <label>
                        <input type="checkbox" value="">
                        Я принимаю <a href="#" data-toggle="modal" data-target="#myOffer">Договор Оферты</a>
                    </label>
                </div>
            </div>

            <div class="form-group form-group-lg">
                <div class="">
{#                    <button type="submit" class="btn btn-default btn-lg" data-toggle="modal" data-target="#myRegisterOk">Зарегистрироваться</button>#}
                    <button type="submit" class="btn btn-default btn-lg">Зарегистрироваться</button>
                </div>
            </div>
        </form>
        </div>

    </section>

    </main>

</div>
</div>
{% endblock %}