apps/eworld/urls.py
__author__ = 'PerminovMA@live.ru'

from django.views.generic import TemplateView
from django.conf.urls import patterns, url, include
from events.rest_api.api_router import router
from eworld import views
from events.views import add_event as add_event_view

urlpatterns = patterns('',
                       url(r'dashboard', TemplateView.as_view(template_name='eworld/dashboard.html'), name='dashboard'),

                       url(r'my_auctions_list', TemplateView.as_view(template_name='eworld/my_auctions_list.html'),
                           name='my_auctions_list'),
                       url(r'auctions_list', TemplateView.as_view(template_name='eworld/auctions_list.html'),
                           name='auctions_list'),
                       url(r'single_auction/(?P<auction_id>[0-9]?)', views.single_auction,
                           name='single_auction'),

                       url(r'my_orders_list', TemplateView.as_view(template_name='eworld/my_orders_list.html'),
                           name='my_orders_list'),
                       url(r'orders_list', TemplateView.as_view(template_name='eworld/orders_list.html'),
                           name='orders_list'),
                       url(r'single_order/(?P<order_id>[0-9]?)', views.single_order,
                           name='single_order'),

                       url(r'add_event', add_event_view, name='add_event'),

                       url(r'rest_api/', include(router.urls, namespace='rest_api_urls')),
                       )

apps/profiles/urls.py
__author__ = 'PerminovMA@live.ru'

from django.conf.urls import url

urlpatterns = [
    url(r'registration', 'profiles.views.user_registration', name='registration'),
    url(r'authorization', 'profiles.views.user_authorization', name='authorization'),
    url(r'logout', 'django.contrib.auth.views.logout', {'next_page': 'index'}, name='logout'),
]

ew/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from profiles import urls as profiles_urls
from eworld import urls as eworld_urls
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='eworld/index.html'), name='index'),
    url(r'^eworld/', include(eworld_urls, namespace='eworld')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^profile/', include(profiles_urls, namespace='profile')),
    url(r'^angular_urls_config$', TemplateView.as_view(template_name='eworld/js/urls_config.js'),
        name='angular_urls_config'),
    # url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                           document_root=settings.STATIC_ROOT)  # Only for development (not production).

apps/eworld/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from random import randint
from django.conf import settings
from eworld.utils import generate_filename
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver
import os


def get_upload_file_path(instance, filename):
    return "attaches/%s/%s/" % (str(randint(1, settings.COUNT_FOLDERS)),
                                str(randint(1, settings.COUNT_FOLDERS))) + generate_filename(filename)


class Attach(models.Model):
    file = models.FileField(upload_to=get_upload_file_path)
    content_type = models.ForeignKey(ContentType)
    object_id = models.CharField(max_length=10)
    content_object = GenericForeignKey()

    def save(self, *args, **kwargs):
        """ delete old file when replacing by updating the file """
        try:
            this = Attach.objects.get(id=self.id)
            if this.file != self.file:
                this.file.delete(save=False)
        except Attach.DoesNotExist:
            pass  # When new photo then we do nothing, normal case
        super(Attach, self).save(*args, **kwargs)

    def filename(self):
        return os.path.basename(self.file.name)


@receiver(pre_delete, sender=Attach)
def attach_file_delete(sender, instance, **kwargs):
    """ delete image when remove object from admin panel """
    instance.file.delete(False)


class FaqSection(models.Model):
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return self.name


class Faq(models.Model):
    section = models.ForeignKey(FaqSection)
    name = models.CharField(max_length=100)
    description = models.TextField()
    video = models.TextField(help_text="iFrame", null=True, blank=True)

    @property
    def short_description(self):
        from django.template.defaultfilters import truncatechars
        return truncatechars(self.description, 100)

    def __unicode__(self):
        return self.name

apps/eworld/views.py
from events.models import AuctionOrder, Order
from django.shortcuts import get_object_or_404, render, HttpResponse
from django.contrib.contenttypes.models import ContentType
from eworld.models import Attach


def single_auction(request, auction_id):
    auction_order = get_object_or_404(AuctionOrder, pk=auction_id)
    auction_categories = auction_order.categories.values_list('name', flat=True)

    auction_content_type = ContentType.objects.get_for_model(auction_order)
    auction_attaches = Attach.objects.filter(content_type__pk=auction_content_type.id, object_id=auction_order.id)
    if auction_order.min_price is None:
        auction_order.min_price = auction_order.start_price / 2

    context = {"auction_order": auction_order,
               "auction_categories": auction_categories,
               "auction_attaches": auction_attaches}
    return render(request, 'eworld/single_auction.html', context)


def single_order(request, order_id):
    order = get_object_or_404(Order, pk=order_id)
    order_categories = order.categories.values_list('name', flat=True)

    order_content_type = ContentType.objects.get_for_model(order)
    order_attaches = Attach.objects.filter(content_type__pk=order_content_type.id, object_id=order.id)

    context = {"order": order, "order_attaches": order_attaches, "order_categories": order_categories}
    return render(request, 'eworld/single_order.html', context)

apps/eworld/templates/eworld/add_event.html
{% extends "eworld/base_template.html" %}
{% load staticfiles %}

{% block stylesheets %}
    {{ block.super }}
    <link rel='stylesheet'  href='{% static "eworld/css/orders_list.css" %}' type='text/css' media='all' />
    <link rel='stylesheet'  href='{% static "jquery-ui-1.11.4/jquery-ui.min.css" %}' type='text/css' media='all' />
{% endblock %}

{% block body %}
    <div class="dashboard" xmlns="http://www.w3.org/1999/html">
    <div class="container-fluid">

        <main id="page">

            {% block menu %}
                {{ block.super }}
            {% endblock %}

            <section id="profile" class="min">
                <header>
                    <div class="cover-overlay" style="background-image: url(https://unsplash.imgix.net/photo-1421779399549-3004b5ad7fa5?dpr=2&fit=crop&fm=jpg&h=600&q=75&w=700)"></div>
                    <a href="#" class="avatar ew-icon-organizer" style="background-image: url(https://ununsplash.imgix.net/photo-1429497587953-2e68f09d4283?dpr=2&fit=crop&fm=jpg&h=225&q=75&w=350);"></a>
                    <button type="button" class="navbar-toggle collapsed ew-icon-open-sub" data-toggle="collapse" data-target="#profile_menu"></button>
                    <h1>{{ user.first_name }} {{ user.last_name }}</h1>
                    <ul class="rating">
                        <li class="on"></li>
                        <li class="on"></li>
                        <li class="on"></li>
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                    </ul>
                </header>
                <ul class="statistic row">
                    <li class="col-md-4 col-sm-12"><span>171</span>просмотры</li>
                    <li class="col-md-4 col-sm-12"><span class="cash">5,00</span>баланс</li>
                    <li class="col-md-4 col-sm-12"><span>3,7</span>рейтинг</li>
                </ul>
                <nav id="profile_menu" class="collapse navbar-collapse">
                    <ul class="nav nav-pills nav-stacked nav-icons">
                        <li><a href="#" class="ew-icon-organizer">Моё резюме</a></li>
                        <li><a href="{% url 'eworld:my_auctions_list' %}" class="ew-icon-reduction">Мои аукционы</a></li>
                        <li><a href="{% url 'eworld:orders_list' %}" class="ew-icon-project">Заказы</a></li>
                        <li><a href="#" class="ew-icon-calendar">Каледнарь занятости</a></li>
                    </ul>
                </nav>
            </section>

    <section id="content" class="single-project">

        <div class="row top30">
            <div class="col-md-10" style="margin-left: 3em;">
                <h1>Создание заказа</h1>
                <form method="POST" class="col-md-9" role="form" enctype="multipart/form-data" action="{% url 'eworld:add_event' %}"> {% csrf_token %}

                    <div class="form-group">
                        {{ form.name.errors }}
                        <input name="{{ form.name.html_name }}" id="{{ form.name.id_for_label }}" type="text" class="form-control input-lg" placeholder="{{ form.name.help_text }}">
                    </div>
                    <div class="form-group top30">
                        {{ form.event_date.errors }}
                        <label for="{{ form.event_date.id_for_label }}">{{ form.event_date.help_text }}</label>
                        <input name="{{ form.event_date.html_name }}" id="{{ form.event_date.id_for_label }}" type="text">
                    </div>
                    <div class="form-group top30">
                        {{ form.price.errors }}
                        <div class="row">
                            <label class="col-md-2" for="{{ form.price.id_for_label }}">{{ form.price.help_text }}</label>
                            <div class="col-md-5" style="display: table">
                                <input name="{{ form.price.html_name }}" type="number" class="form-control" id="{{ form.price.id_for_label }}" placeholder="{{ form.price.help_text }}" value="0" min="0"><div class="input-group-addon">&nbsp;руб.</div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group top30">
                        {{ form.city.errors }}
                        <p class="ew-icon ew-icon-city">
                            {{ form.city }}
                        </p>
                    </div>
                    <div class="form-group top50">
                        {{ form.categories.errors }}
                        <label for="{{ form.categories.id_for_label }}">{{ form.categories.help_text }}</label>

                        <div class="row">
                            {% for category in categories_set %}
                                <div class="left30 col-md-4 top10">
                                    <img src="{{category.icon.url}}" width="40em;" height="40em;"/>
                                    <input id="{{ form.categories.id_for_label }}" name="{{ form.categories.html_name }}" type="checkbox" value="{{ category.pk }}"/><span class="left5">{{category.name}}</span>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-group top50">
                        {{ form.files.errors }}
                        <p class="ew-icon ew-icon-attach">
                            {{ form.files }}
                        </p>
                    </div>
                    <div class="form-group top30">
                        {{ form.description.errors }}
                        <textarea id="{{ form.description.id_for_label }}" name="{{ form.description.html_name }}" class="form-control input-lg" placeholder="{{ form.description.help_text }}" rows="3"></textarea>
                    </div>
                    <div class="form-group top30">
                        {{ form.requirements.errors }}
                        <textarea id="{{ form.requirements.id_for_label }}" name="{{ form.requirements.html_name }}" class="form-control input-lg" placeholder="{{ form.requirements.help_text }}" rows="3"></textarea>
                    </div>

                    <button type="submit" class="btn btn-default btn-lg">Опубликовать проект</button>
                </form>
            </div>
        </div>

{#                    <div class="checkbox">#}
{#                        <label class="ew-icon-transport">#}
{#                            <input type="checkbox" value="">Транспорт#}
{#                        </label>#}
{#                    </div>#}
{#                    <div class="checkbox">#}
{#                        <label class="ew-icon-video">#}
{#                            <input type="checkbox" value="">Видеосьёмка#}
{#                        </label>#}
{#                    </div>#}
{#                    <div class="checkbox">#}
{#                        <label class="ew-icon-makeup">#}
{#                            <input type="checkbox" value="">Стилисты#}
{#                        </label>#}
{#                    </div>#}
{#                    <div class="checkbox">#}
{#                        <label class="ew-icon-jewelry">#}
{#                            <input type="checkbox" value="">Ювелирные изделия#}
{#                        </label>#}
{#                    </div>#}
{#                    <div class="checkbox">#}
{#                        <label class="ew-icon-halls">#}
{#                            <input type="checkbox" value="">Рестораны#}
{#                        </label>#}
{#                    </div>#}
{#                    <div class="checkbox">#}
{#                        <label class="ew-icon-walk">#}
{#                            <input type="checkbox" value="">Места прогулок#}
{#                        </label>#}
{#                    </div>#}
{#                    <div class="checkbox">#}
{#                        <label class="ew-icon-boat">#}
{#                            <input type="checkbox" value="">Тепоходы#}
{#                        </label>#}
{#                    </div>#}
{#                    <div class="checkbox">#}
{#                        <label class="ew-icon-wd">#}
{#                            <input type="checkbox" value="">Свадебные платья#}
{#                        </label>#}
{#                    </div>#}
{#                    <div class="checkbox">#}
{#                        <label class="ew-icon-transport">#}
{#                            <input type="checkbox" value="">Реквизиты для меропреятий#}
{#                        </label>#}
{#                    </div>#}
{#                    <div class="checkbox">#}
{#                        <label class="ew-icon-transport">#}
{#                            <input type="checkbox" value="">Отели#}
{#                        </label>#}
{#                    </div>#}
{#                    <div class="checkbox">#}
{#                        <label class="ew-icon-transport">#}
{#                            <input type="checkbox" value="">Заказ тортов#}
{#                        </label>#}
{#                    </div>#}
{#                    <div class="checkbox">#}
{#                        <label class="ew-icon-transport">#}
{#                            <input type="checkbox" value="">Заказ букетов#}
{#                        </label>#}
{#                    </div>#}
{#                    <div class="checkbox">#}
{#                        <label class="ew-icon-transport">#}
{#                            <input type="checkbox" value="">Оформление помещений#}
{#                        </label>#}
{#                    </div>#}
{#                    <div class="checkbox">#}
{#                        <label class="ew-icon-transport">#}
{#                            <input type="checkbox" value="">Свадьба, Венчание#}
{#                        </label>#}
{#                    </div>#}
{#                    <div class="checkbox">#}
{#                        <label class="ew-icon-transport">#}
{#                            <input type="checkbox" value="">Меропреятия за границей#}
{#                        </label>#}
{#                    </div>#}
{#                    <div class="checkbox">#}
{#                        <label class="">#}
{#                            <input type="checkbox" value="">Кейтеринг#}
{#                        </label>#}
{#                    </div>#}


    </section>

    </main>

    </div>
    </div>
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script src="{% static 'jquery-ui-1.11.4/jquery-ui.min.js' %}"></script>
    <script type="text/javascript">
        $("#{{ form.city.id_for_label }}").addClass("form-control");

        $(function () {
            $("#{{ form.event_date.id_for_label }}").datepicker({
                showOn: "both",
                buttonImage: "{% static 'images/calendar_icon.png' %}",
                buttonImageOnly: true,
                buttonText: "Select date",
                changeMonth: true,
                changeYear: true,
                dateFormat: "dd/mm/yy",
                firstDay: 1, // Set the first day of the week: Sunday is 0, Monday is 1, etc.
                defaultDate: +7,
            });

            // $("#{{ form.event_date.id_for_label }}").datepicker('setDate', new Date()); // default value
        });
    </script>
{% endblock %}

apps/eworld/templates/eworld/orders_list.html
{% extends "eworld/base_template.html" %}
{% load staticfiles %}

{% block stylesheets %}
    {{ block.super }}
    <link rel='stylesheet'  href='{% static "eworld/css/orders_list.css" %}' type='text/css' media='all' />
{% endblock %}

{% block body %}
    <div class="dashboard" xmlns="http://www.w3.org/1999/html" ng-controller="OrdersListController">
    <div class="container-fluid">

        <main id="page">
            {% block menu %}
                {{ block.super }}
            {% endblock %}

            <section id="profile" class="min">
                <header>
                    <div class="cover-overlay" style="background-image: url(https://unsplash.imgix.net/photo-1421779399549-3004b5ad7fa5?dpr=2&fit=crop&fm=jpg&h=600&q=75&w=700)"></div>
                    <a href="#" class="avatar ew-icon-organizer" style="background-image: url(https://ununsplash.imgix.net/photo-1429497587953-2e68f09d4283?dpr=2&fit=crop&fm=jpg&h=225&q=75&w=350);"></a>
                    <button type="button" class="navbar-toggle collapsed ew-icon-open-sub" data-toggle="collapse" data-target="#profile_menu"></button>
                    <h1>{{ user.first_name }} {{ user.last_name }}</h1>
                    <ul class="rating">
                        <li class="on"></li>
                        <li class="on"></li>
                        <li class="on"></li>
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                    </ul>
                </header>
                <ul class="statistic row">
                    <li class="col-lg-4 col-md-4 col-sm-12"><span>171</span>просмотры</li>
                    <li class="col-lg-4 col-md-4 col-sm-12"><span class="cash">5,00</span>баланс</li>
                    <li class="col-lg-4 col-md-4 col-sm-12"><span>3,8</span>рейтинг</li>
                </ul>
                <nav id="profile_menu" class="collapse navbar-collapse">
                    <ul class="nav nav-pills nav-stacked nav-icons">
                        <li><a href="#" class="ew-icon-organizer">Моё резюме</a></li>
                        <li><a href="{% url 'eworld:my_orders_list' %}" class="ew-icon-project">Мои заказы</a></li>
                        <li><a href="{% url 'eworld:auctions_list' %}" class="ew-icon-reduction">Аукционы</a></li>
                        <li><a href="#" class="ew-icon-calendar">Каледнарь занятости</a></li>
                    </ul>
                </nav>
            </section>

            <section id="content">
                <header class="clearfix">
                    <div class="row">
                            <span class="col-md-1 order_icon"></span>
                            <h1 class="col-md-2">Заказы</h1>
                        <a href="{% url 'eworld:add_event' %}" class="btn btn-outline btn-lg inverse col-md-offset-7 col-md-2">Создать заказ</a>
                    </div>


                    <nav id="filter" class="navbar">
                        <ul class="nav navbar-nav">
                            <li class="dropdown"><a href="#" class="dropdown-toggle btn-select" data-toggle="dropdown" role="button" aria-expanded="false"><span class="label-text">Все категории</span> <span class="caret"></span></a>
                                <div class="dropdown-menu dropdown-select">
                                    <ul class="nav nav-pills nav-stacked nav-icons" role="menu">
                                        <li ng-repeat="orderType in orderTypes" ng-click="setOrderTypeSelected(orderType)"><a href="#" class="ew-order-icon" style="background-image: url([[orderType.icon]]);">[[orderType.name]]</a></li>
                                        <li class="divider"></li>
                                        <li ng-click="setOrderTypeSelected(null)"><a href="#">Все категории</a></li>
                                    </ul>
                                </div>
                            </li>
                            <li class="dropdown"><a href="#" class="dropdown-toggle btn-select" data-toggle="dropdown" role="button" aria-expanded="false"><span class="label-text">Порядок</span> <span class="caret"></span></a>
                                <div class="dropdown-menu dropdown-select">
                                    <ul class="nav nav-pills nav-stacked nav-icons" role="menu" ng-click="getAuctionsList()">
                                        <li><a href="#" ng-click="sortOrder = 'by_newest'">Самые свежие</a></li>
{#                                        <li><a href="#" ng-click="sortOrder = 'by_views'">Самые просматриваемые</a></li>#}
                                        <li class="divider"></li>
                                        <li><a href="#" ng-click="sortOrder = 'this_day'">Сегодня</a></li>
                                        <li><a href="#" ng-click="sortOrder = 'this_week'">За неделю</a></li>
                                    </ul>
                                </div>
                            </li>
                            <form class="navbar-form navbar-left" role="search">
                                <div class="form-group">
                                    <input type="text" ng-model="selectedCity" class="form-control input-lg" placeholder="Город">
                                </div>

                            </form>
                        </ul>
                    </nav>

                    <div class="description col-lg-7 col-md-9">
                        <p>Minimalist posters are encouraging us to be design idiots.</p>
                        <p>A central tenet of good design is that it shouldn't be any more complicated than it needs to be, but that doesn't mean good design is inherently uncomplicated.</p>
                    </div>
                </header>
                <div class="project-list">
                    <article class="project-item" ng-repeat="order in orders">
                        <header>
                            <h2><a href="{% url 'eworld:single_order' '' %}[[order.id]]">[[order.name]]</a></h2>
                        </header>
                        <p>[[order.description]]</p>
                        <footer>
                        <p class="lead price">[[order.price]] руб.</p>
                            <p class="meta"><a href="#" class="user"><img src="[[order.owner.user.avatar]]" class="avatar img-circle" />[[order.owner.user.first_name + ' ' + order.owner.user.last_name]], [[order.city.name]]</a> <time>[[order.event_date | date: 'dd.MM.yyyy h:mm']]</time><span class="preview ew-icon-eye-small">[[order.order_views_count]]</span></p>
                        </footer>
                    </article>

{#                    <article class="project-item">#}
{#                        <header>#}
{#                            <h2><a href="#">Project title example</a></h2>#}
{#                        </header>#}
{#                        <p>On Friday, at South by Southwest, all that will change. For the duration of the festival, Spotify House will be arrayed in a bold and explosively colorful new brand identity, which was the result of a year's worth of work, and many trips to the company’s Stockholm headquarters, by the New York design firm, Collins.</p>#}
{#                        <footer>#}
{#                            <p class="lead price">10 000 руб.</p>#}
{#                            <p class="meta"><a href="#" class="user"><img src="images/avatar.jpg" class="avatar img-circle" />User Name, Санкт-Петербург</a> <time>15&nbsp;апр,&nbsp;2015&nbsp;11:37</time><span class="preview ew-icon-eye-small">17</span></p>#}
{#                        </footer>#}
{#                    </article>#}
{#                    <article class="project-item">#}
{#                        <header>#}
{#                            <h2><a href="#">Project title example</a></h2>#}
{#                        </header>#}
{#                        <p>On Friday, at South by Southwest, all that will change. For the duration of the festival, Spotify House will be arrayed in a bold and explosively colorful new brand identity, which was the result of a year's worth of work, and many trips to the company’s Stockholm headquarters, by the New York design firm, Collins.</p>#}
{#                        <footer>#}
{#                            <p class="lead price">10 000 руб.</p>#}
{#                            <p class="meta"><a href="#" class="user"><img src="images/avatar.jpg" class="avatar img-circle" />User Name, Санкт-Петербург</a> <time>15&nbsp;апр,&nbsp;2015&nbsp;11:37</time><span class="preview ew-icon-eye-small">17</span></p>#}
{#                        </footer>#}
{#                    </article>#}
{#                    <article class="project-item upd closed">#}
{#                        <header>#}
{#                            <h2><a href="#">Project title example</a></h2>#}
{#                        </header>#}
{#                        <p>On Friday, at South by Southwest, all that will change. For the duration of the festival, Spotify House will be arrayed in a bold and explosively colorful new brand identity, which was the result of a year's worth of work, and many trips to the company’s Stockholm headquarters, by the New York design firm, Collins.</p>#}
{#                        <footer>#}
{#                            <span class="label label-default">Акуцион закрыт</span>#}
{#                            <p class="lead price">10 000 руб.</p>#}
{#                            <p class="meta"><a href="#" class="user ew-icon-organizer">User Name, Санкт-Петербург</a> <time>15&nbsp;апр,&nbsp;2015&nbsp;11:37</time><span class="preview ew-icon-eye-small">37</span></p>#}
{#                        </footer>#}
{#                    </article>#}
                </div>
        <!--    <footer class="inverse">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12 col-lg-push-5 col-md-push-5">

                                <p class="support-info phone_icon"><span itemprop="telephone">+7(435) 435 56 56</span><span itemprop="email">info@eworld.com</span></p>
                            </div>
                            <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12 col-lg-pull-2 col-md-pull-2 text-right">

                                <a href="#" class="btn btn-outline btn-lg inverse">Регистрация</a>
                                <a href="#" class="btn btn-outline btn-lg inverse">Вход</a>
                                <ul class="social nav nav-pills">
                                    <li><a href="#" class="brandico-twitter-bird"></a></li>
                                    <li><a href="#" class="brandico-facebook"></a></li>
                                    <li><a href="#" class="brandico-googleplus-rect"></a></li>
                                    <li><a href="#" class="brandico-odnoklassniki"></a></li>
                                    <li><a href="#" class="brandico-vkontakte-rect"></a></li>
                                    <li><a href="#" class="brandico-instagram-filled"></a></li>
                                </ul>
                            </div>
                            <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12">
                                <ul class="nav nav-pills nav-stacked">
                                    <li><a href="#">Реквизиты</a></li>
                                    <li><a href="#">Договор оферты для Заказчиков</a></li>
                                    <li><a href="#">Договор оферты для исполнителей</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </footer> -->
            </section>

        </main>

    </div>
    </div>
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script src="{% static 'eworld/js/angular/controllers/OrdersListController.js' %}"></script>
    <script src="{% static 'eworld/js/angular/services/EventsServices.js' %}"></script>
{% endblock %}